# fly.toml app configuration file generated for hono-vite-project on 2024-05-04T23:41:45+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hono-vite-project'
primary_region = 'otp'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
